CREATE TABLE `webshare` (
	`uri` VARCHAR(50) NOT NULL,
	`type` VARCHAR(50) NOT NULL,
	`value` VARCHAR(200) NOT NULL,
	`password` VARCHAR(200) NULL DEFAULT NULL,
	`expireDate` DATETIME NULL DEFAULT NULL,
	`createDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`uri`)
) ENGINE = InnoDB;